@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.legacyponder.utils;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;