@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.legacyponder.structure.events;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;