@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.legacyponder.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;