@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.legacyponder.quests;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;