@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.legacyponder.crafttweaker;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;